import { Component, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { Api } from '../../core/api';
import { User } from '../../core/models';
@Component({imports:[ReactiveFormsModule,MatButtonModule,MatFormFieldModule,MatInputModule],template:`<div class="auth-layout"><section class="auth-story"><div class="brand">daily ·</div><div><p class="eyebrow">A CLEARER PICTURE OF YOUR DAY</p><h1>Good work deserves<br>a place to live.</h1><p>Capture your progress. Untangle your thoughts.<br>Carry the important things forward.</p></div><small>YOUR NOTES. YOUR PROGRESS. YOUR SPACE.</small></section><section class="auth-form"><p class="eyebrow">DAILY WORK NOTES</p><h1>{{register()?'Create your workspace':'Welcome back.'}}</h1><p class="muted">{{register()?'Start with an email and a secure password.':'A fresh perspective on everything you’re working on.'}}</p><form [formGroup]="form" (ngSubmit)="submit()"><mat-form-field appearance="outline"><mat-label>Email address</mat-label><input matInput type="email" formControlName="email" autocomplete="email"></mat-form-field><mat-form-field appearance="outline"><mat-label>Password</mat-label><input matInput type="password" formControlName="password" [attr.autocomplete]="register()?'new-password':'current-password'"><mat-hint>At least 12 characters for a new account</mat-hint></mat-form-field>@if(error()){<p class="error" role="alert">{{error()}}</p>}<button mat-flat-button [disabled]="busy()||form.invalid">{{busy()?'Please wait…':register()?'Create account':'Sign in'}} <span>→</span></button></form><button mat-button (click)="register.set(!register())">{{register()?'Already have an account? Sign in':'New here? Create an account'}}</button></section></div>`})
export class Auth {api=inject(Api);fb=inject(FormBuilder);register=signal(false);busy=signal(false);error=signal('');form=this.fb.nonNullable.group({email:['',[Validators.required,Validators.email]],password:['',[Validators.required]]});submit(){if(this.form.invalid||this.busy())return;this.busy.set(true);this.error.set('');this.api.post<User>('/auth/'+(this.register()?'register':'login'),this.form.getRawValue()).subscribe({next:u=>{this.api.user.set(u);void this.api.router.navigateByUrl('/')},error:e=>{this.error.set(this.api.error(e));this.busy.set(false)}})}}
