// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Attachment struct {
	ID         string             `json:"id"`
	NoteID     string             `json:"note_id"`
	UserID     string             `json:"user_id"`
	Name       string             `json:"name"`
	Mime       string             `json:"mime"`
	Size       int64              `json:"size"`
	StorageKey string             `json:"storage_key"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type EmailAttempt struct {
	ID             string             `json:"id"`
	UserID         string             `json:"user_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	Fingerprint    string             `json:"fingerprint"`
	Recipients     []byte             `json:"recipients"`
	Subject        string             `json:"subject"`
	Outcome        string             `json:"outcome"`
	Detail         string             `json:"detail"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type FileDeletion struct {
	StorageKey string             `json:"storage_key"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Note struct {
	ID          string             `json:"id"`
	UserID      string             `json:"user_id"`
	WorkDate    pgtype.Date        `json:"work_date"`
	Title       string             `json:"title"`
	Project     string             `json:"project"`
	Description string             `json:"description"`
	Tasks       []byte             `json:"tasks"`
	Status      string             `json:"status"`
	Priority    string             `json:"priority"`
	Tags        []string           `json:"tags"`
	Minutes     int32              `json:"minutes"`
	Blockers    string             `json:"blockers"`
	NextSteps   string             `json:"next_steps"`
	Version     int32              `json:"version"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Project struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
	Name   string `json:"name"`
	Color  string `json:"color"`
}

type Session struct {
	TokenHash string             `json:"token_hash"`
	UserID    string             `json:"user_id"`
	Csrf      string             `json:"csrf"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type User struct {
	ID           string             `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Timezone     string             `json:"timezone"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
