// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNote = `-- name: CreateNote :one
INSERT INTO notes(id,user_id,work_date,title,project,description,tasks,status,priority,tags,minutes,blockers,next_steps)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING id, user_id, work_date, title, project, description, tasks, status, priority, tags, minutes, blockers, next_steps, version, created_at, updated_at
`

type CreateNoteParams struct {
	ID          string      `json:"id"`
	UserID      string      `json:"user_id"`
	WorkDate    pgtype.Date `json:"work_date"`
	Title       string      `json:"title"`
	Project     string      `json:"project"`
	Description string      `json:"description"`
	Tasks       []byte      `json:"tasks"`
	Status      string      `json:"status"`
	Priority    string      `json:"priority"`
	Tags        []string    `json:"tags"`
	Minutes     int32       `json:"minutes"`
	Blockers    string      `json:"blockers"`
	NextSteps   string      `json:"next_steps"`
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, createNote,
		arg.ID,
		arg.UserID,
		arg.WorkDate,
		arg.Title,
		arg.Project,
		arg.Description,
		arg.Tasks,
		arg.Status,
		arg.Priority,
		arg.Tags,
		arg.Minutes,
		arg.Blockers,
		arg.NextSteps,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkDate,
		&i.Title,
		&i.Project,
		&i.Description,
		&i.Tasks,
		&i.Status,
		&i.Priority,
		&i.Tags,
		&i.Minutes,
		&i.Blockers,
		&i.NextSteps,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNote = `-- name: DeleteNote :execrows
DELETE FROM notes WHERE id=$1 AND user_id=$2 AND version=$3
`

type DeleteNoteParams struct {
	ID      string `json:"id"`
	UserID  string `json:"user_id"`
	Version int32  `json:"version"`
}

func (q *Queries) DeleteNote(ctx context.Context, arg DeleteNoteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNote, arg.ID, arg.UserID, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getNote = `-- name: GetNote :one
SELECT id, user_id, work_date, title, project, description, tasks, status, priority, tags, minutes, blockers, next_steps, version, created_at, updated_at FROM notes WHERE id = $1 AND user_id = $2
`

type GetNoteParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetNote(ctx context.Context, arg GetNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, getNote, arg.ID, arg.UserID)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkDate,
		&i.Title,
		&i.Project,
		&i.Description,
		&i.Tasks,
		&i.Status,
		&i.Priority,
		&i.Tags,
		&i.Minutes,
		&i.Blockers,
		&i.NextSteps,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotes = `-- name: ListNotes :many
SELECT id, user_id, work_date, title, project, description, tasks, status, priority, tags, minutes, blockers, next_steps, version, created_at, updated_at FROM notes WHERE user_id = $1
AND ($2::text = '' OR (title || ' ' || description || ' ' || project || ' ' || array_to_string(tags,' ')) ILIKE '%' || $2 || '%')
AND ($3::text = '' OR work_date >= NULLIF($3,'')::date)
AND ($4::text = '' OR work_date <= NULLIF($4,'')::date)
AND ($5::text = '' OR project = $5)
AND ($6::text = '' OR status = $6)
AND ($7::text = '' OR priority = $7)
AND ($8::text = '' OR $8 = ANY(tags))
ORDER BY
 CASE WHEN $9::text = 'title' THEN title END ASC,
 CASE WHEN $9::text = 'priority' THEN CASE priority WHEN 'high' THEN 3 WHEN 'medium' THEN 2 ELSE 1 END END DESC,
 CASE WHEN $9::text = 'updated' THEN updated_at END DESC,
 work_date DESC,id
LIMIT $11 OFFSET $10
`

type ListNotesParams struct {
	Owner          string `json:"owner"`
	Search         string `json:"search"`
	FromDate       string `json:"from_date"`
	ToDate         string `json:"to_date"`
	ProjectFilter  string `json:"project_filter"`
	StatusFilter   string `json:"status_filter"`
	PriorityFilter string `json:"priority_filter"`
	TagFilter      string `json:"tag_filter"`
	SortBy         string `json:"sort_by"`
	PageOffset     int32  `json:"page_offset"`
	PageSize       int32  `json:"page_size"`
}

func (q *Queries) ListNotes(ctx context.Context, arg ListNotesParams) ([]Note, error) {
	rows, err := q.db.Query(ctx, listNotes,
		arg.Owner,
		arg.Search,
		arg.FromDate,
		arg.ToDate,
		arg.ProjectFilter,
		arg.StatusFilter,
		arg.PriorityFilter,
		arg.TagFilter,
		arg.SortBy,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WorkDate,
			&i.Title,
			&i.Project,
			&i.Description,
			&i.Tasks,
			&i.Status,
			&i.Priority,
			&i.Tags,
			&i.Minutes,
			&i.Blockers,
			&i.NextSteps,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNote = `-- name: UpdateNote :one
UPDATE notes SET work_date=$3,title=$4,project=$5,description=$6,tasks=$7,status=$8,priority=$9,tags=$10,minutes=$11,blockers=$12,next_steps=$13,version=version+1,updated_at=now()
WHERE id=$1 AND user_id=$2 AND version=$14 RETURNING id, user_id, work_date, title, project, description, tasks, status, priority, tags, minutes, blockers, next_steps, version, created_at, updated_at
`

type UpdateNoteParams struct {
	ID          string      `json:"id"`
	UserID      string      `json:"user_id"`
	WorkDate    pgtype.Date `json:"work_date"`
	Title       string      `json:"title"`
	Project     string      `json:"project"`
	Description string      `json:"description"`
	Tasks       []byte      `json:"tasks"`
	Status      string      `json:"status"`
	Priority    string      `json:"priority"`
	Tags        []string    `json:"tags"`
	Minutes     int32       `json:"minutes"`
	Blockers    string      `json:"blockers"`
	NextSteps   string      `json:"next_steps"`
	Version     int32       `json:"version"`
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, updateNote,
		arg.ID,
		arg.UserID,
		arg.WorkDate,
		arg.Title,
		arg.Project,
		arg.Description,
		arg.Tasks,
		arg.Status,
		arg.Priority,
		arg.Tags,
		arg.Minutes,
		arg.Blockers,
		arg.NextSteps,
		arg.Version,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkDate,
		&i.Title,
		&i.Project,
		&i.Description,
		&i.Tasks,
		&i.Status,
		&i.Priority,
		&i.Tags,
		&i.Minutes,
		&i.Blockers,
		&i.NextSteps,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
